### ISSUE TITLE
Split doesn't work with backslash

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-filter-mutate#109]
- Version: 5.6 or 6.x
- Operating System: Any

Backslashes doesn't work with the split filter:

```

  mutate{
    split=>[
      "testfield",
      "\"
    ]
  }
```

I've tried with different approaches and they don't work. Also used the `config.support_escapes: true` configuration to see if that helps. But doesn't seems to be possible. The only workaround was to `gsub` the field first to remove the backslashes.

**Comment by jsvd** [comment]
Here's a simple reproduction (same result with and without `config.support_escapes`):

```
/tmp/logstash-6.1.0 % bin/logstash -e 'filter { mutate { split => { "message" => "\\" } } }'
Sending Logstash's logs to /tmp/logstash-6.1.0/logs which is now configured via log4j2.properties
[2017-12-15T13:26:45,203][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/tmp/logstash-6.1.0/modules/fb_apache/configuration"}
[2017-12-15T13:26:45,224][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/tmp/logstash-6.1.0/modules/netflow/configuration"}
[2017-12-15T13:26:45,521][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-12-15T13:26:46,288][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.0"}
[2017-12-15T13:26:46,828][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-12-15T13:26:47,230][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of \\\", \", any character at line 3, column 53 (byte 128) after filter { mutate { split => { \"message\" => \"\\\\\" } } }", :backtrace=>["/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:42:in `compile_imperative'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:50:in `compile_graph'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline.rb:51:in `initialize'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "/tmp/logstash-6.1.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by jsvd** [comment]
I'm moving this to core as the error is showing up on the configuration parser.

**Comment by gmoskovicz** [comment]
Thanks for that @jsvd !

**Comment by jsvd** [comment]
Migrated to https://github.com/elastic/logstash/issues/8843
