### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-mutate#11]
From https://github.com/elasticsearch/logstash/issues/2487

```
  26) LogStash::Filters::Mutate regression - mutate should lowercase a field created by grok "HELLO WORLD" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "hello", but got nil
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```

**Comment by wiibaa** [comment]
Most probably a side effect of grok failing spec too where a pattern files is written in the logstash local gem !!!

**Comment by ph** [comment]
Fixed with grok https://github.com/logstash-plugins/logstash-filter-grok/issues/9 

@wiibaa yup side effect.
