### ISSUE TITLE
Crashes Logstash when sprintf-generated gsub pattern is an invalid regexp

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-filter-mutate#122]
Initially reported by Suman Reddy [via Discuss](https://discuss.elastic.co/t/asterisk-in-mutate-with-gsub/126300)

Given the following configuration, when the gsub directive builds an invalid regexp via sprintf, the Pipeline crashes and shuts down:

~~~
input {
  generator {
    count => 10
    codec => json
    lines => ['{"message":"foo", "docNumber":"*", "docNumberMasked":"WHATEVER"}']
  }
}
filter {
  mutate {
    gsub => ["message", "%{docNumber}", "%{docNumberMasked}"]
  }
}
output {
  stdout {
    codec => rubydebug
  }
}
~~~

Logs:

~~~
╭─{ yaauie@castrovel:~/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp }
╰─○ logstash-6.2.2/bin/logstash -f invalid-generated-gsub-expression.conf
Sending Logstash's logs to /Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logs which is now configured via log4j2.properties
[2018-04-05T18:27:32,636][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/modules/fb_apache/configuration"}
[2018-04-05T18:27:32,653][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/modules/netflow/configuration"}
[2018-04-05T18:27:32,845][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-04-05T18:27:33,560][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.2"}
[2018-04-05T18:27:33,985][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-04-05T18:27:37,050][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-04-05T18:27:37,178][INFO ][logstash.pipeline        ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,268][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,484][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,486][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"target of repeat operator is not specified: /*/", "backtrace"=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"], :thread=>"#<Thread:0x46d1a37d sleep>"}
[2018-04-05T18:27:37,513][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x46d1a37d run>"}
[2018-04-05T18:27:37,673][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<RegexpError: target of repeat operator is not specified: /*/>, :backtrace=>["org/jruby/RubyRegexp.java:918:in `initialize'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:339:in `gsub_dynamic_fields'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:327:in `block in gsub'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:309:in `gsub'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:223:in `filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47:in `multi_filter'", "(eval):42:in `block in filter_func'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447:in `filter_batch'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/Users/yaauie/src/elastic/discuss-scratch/126300-gsub-crash-invalid-regexp/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"]}
[2018-04-05T18:27:37,731][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit
~~~

**Comment by VarshaHotkar** [comment]
gsub syntax was missing, please check below conf

input {
  generator {
    count => 10
    codec => json
    lines => ['{"message":"foo", "docNumber":"*", "docNumberMasked":"WHATEVER"}']
  }
}
filter {

  mutate {
    gsub => ["message", "docNumber", "docNumberMasked"]
  }
}
output {
  stdout {
    codec => rubydebug
  }
}
